//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ModelFirstModel1", "FK_StudentKardex", "students", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MySql.Data.Entity.Tests.Student), "kardexes", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MySql.Data.Entity.Tests.Kardex))]

// Original file name:
// Generation date: 21/06/2012 06:46:51 p.m.
namespace MySql.Data.Entity.Tests
{
    
    /// <summary>
    /// There are no comments for ModelFirstModel1Container in the schema.
    /// </summary>
    public partial class ModelFirstModel1Container : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ModelFirstModel1Container object using the connection string found in the 'ModelFirstModel1Container' section of the application configuration file.
        /// </summary>
        public ModelFirstModel1Container() : 
                base("name=ModelFirstModel1Container", "ModelFirstModel1Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ModelFirstModel1Container object.
        /// </summary>
        public ModelFirstModel1Container(string connectionString) : 
                base(connectionString, "ModelFirstModel1Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ModelFirstModel1Container object.
        /// </summary>
        public ModelFirstModel1Container(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ModelFirstModel1Container")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Kardexes in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Kardex> Kardexes
        {
            get
            {
                if ((this._Kardexes == null))
                {
                    this._Kardexes = base.CreateQuery<Kardex>("[Kardexes]");
                }
                return this._Kardexes;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Kardex> _Kardexes;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Student>("[Students]");
                }
                return this._Students;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Student> _Students;
        /// <summary>
        /// There are no comments for Kardexes in the schema.
        /// </summary>
        public void AddToKardexes(Kardex kardex)
        {
            base.AddObject("Kardexes", kardex);
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    }
    /// <summary>
    /// There are no comments for ModelFirstModel1.Kardex in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ModelFirstModel1", Name="Kardex")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Kardex : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Kardex object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="score">Initial value of Score.</param>
        public static Kardex CreateKardex(int id, double score)
        {
            Kardex kardex = new Kardex();
            kardex.Id = id;
            kardex.Score = score;
            return kardex;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Score in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Score
        {
            get
            {
                return this._Score;
            }
            set
            {
                this.OnScoreChanging(value);
                this.ReportPropertyChanging("Score");
                this._Score = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Score");
                this.OnScoreChanged();
            }
        }
        private double _Score;
        partial void OnScoreChanging(double value);
        partial void OnScoreChanged();
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ModelFirstModel1", "FK_StudentKardex", "students")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Student Students
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("ModelFirstModel1.FK_StudentKardex", "students").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("ModelFirstModel1.FK_StudentKardex", "students").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Student> StudentsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Student>("ModelFirstModel1.FK_StudentKardex", "students");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Student>("ModelFirstModel1.FK_StudentKardex", "students", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ModelFirstModel1.Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ModelFirstModel1", Name="Student")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Student : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Student CreateStudent(int id, string name)
        {
            Student student = new Student();
            student.Id = id;
            student.Name = name;
            return student;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Kardexes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ModelFirstModel1", "FK_StudentKardex", "kardexes")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Kardex> Kardexes
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Kardex>("ModelFirstModel1.FK_StudentKardex", "kardexes");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Kardex>("ModelFirstModel1.FK_StudentKardex", "kardexes", value);
                }
            }
        }
    }
}
